import { Router } from "express";
import BrandRouter from "./brand.routes.js";
import CategoryRouter from "./category.routes.js";
import CityRouter from "./city.routes.js";
import ItemRouter from "./item.routes.js";
import ClientRouter from "./client.routes.js";
import DeliveryRouter from "./delivery.routes.js";
import ManagerRouter from "./manager.routes.js";
import OrderRouter from "./order.routes.js";
import PaymentRouter from "./payment.routes.js";
import PromocodeRouter from "./promocode.routes.js";
import ReviewRouter from "./review.routes.js";
import ServiceRouter from "./service.routes.js";
import StatusRouter from "./status.routes.js";
import StreetRouter from "./street.routes.js";
import FavoriteRouter from "./favorite.routes.js";
import BasketRouter from "./basket.routes.js";
import ImageRouter from "./image.routes.js";
import RoleRouter from "./role.routes.js";

const EntrypointRoutes = Router();
EntrypointRoutes.use("/api", BrandRouter);
EntrypointRoutes.use("/api", CategoryRouter);
EntrypointRoutes.use("/api", CityRouter);
EntrypointRoutes.use("/api", ItemRouter);
EntrypointRoutes.use("/api", ClientRouter);
EntrypointRoutes.use("/api", DeliveryRouter);
EntrypointRoutes.use("/api", ManagerRouter);
EntrypointRoutes.use("/api", OrderRouter);
EntrypointRoutes.use("/api", PaymentRouter);
EntrypointRoutes.use("/api", PromocodeRouter);
EntrypointRoutes.use("/api", ReviewRouter);
EntrypointRoutes.use("/api", ServiceRouter);
EntrypointRoutes.use("/api", StatusRouter);
EntrypointRoutes.use("/api", StreetRouter);
EntrypointRoutes.use("/api", FavoriteRouter);
EntrypointRoutes.use("/api", BasketRouter);
EntrypointRoutes.use("/api", ImageRouter);
EntrypointRoutes.use("/api", RoleRouter);
export default EntrypointRoutes